spring.application.name=api

# 1. Configuración de la conexión a MongoDB
spring.mongodb.uri=mongodb://localhost:27017/db_gestion_usuarios

# 2. Mostrar los comandos en la consola 
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# 3. Configuración de la creación automática de índices 
spring.data.mongodb.auto-index-creation=true



# JWT Configuration
application.security.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWp3dC1zZWNyZXQta2V5LWZvci1wb3RvYm9nb3Rh}
application.security.jwt.expiration=${JWT_EXPIRATION_MS:86400000}

